### PR TITLE
feat: basic functions finished

### PR DESCRIPTION
**Pull request by ffyuanda**
For now, the OAuth basic functions are finished, can refer to the latest README.md

We still have to add some configs, for which I need some help to finalize these options (**Authentication URL** and **Validation URL**) :

image

Signed-off-by: ffyuanda <46557895+ffyuanda@users.noreply.github.com>

### CODE REVIEW

**Comment by ffyuanda** [comment]
@hsluoyz plz review

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by hsluoyz** [comment]
@ffyuanda you should setup a Casdoor instance to learn it: https://door.casbin.com/ , and do you have demo link for your Odoo integration? Ideally I expect to see a Odoo link and a Casdoor link.

**Comment by ffyuanda** [comment]
@hsluoyz I'm trying to serve my localhost on ngrok, but it has a catch that it cannot serve more than 20 connections in a minute.   

Here is the [website](https://7ebcd43167dd.ngrok.io)

username: admin
password: admin

If it shows Too Many Connections, you gonna have to wait for a minute.

For the two URLs, I still have no clues where should I find them after kicking around the [door.casbin.com](https://door.casbin.com/) website. Hope you don't mind give me some hints.

**Comment by hsluoyz** [comment]
@ffyuanda demo link?

**Comment by ffyuanda** [comment]
@hsluoyz  http://test.casbin.com:8069/web/login I'm still stuck at the actual verification step.

**Comment by ffyuanda** [comment]
@hsluoyz test it out at: http://test.casbin.com:8069/web/login,
casdoor username: admin password: 12345678

**Comment by ffyuanda** [comment]
@hsluoyz I think we can merge this PR now since the basic functionalities are added. And I will update the README.md file later.

**Pull request merged**
